import random

daftar_khodam = [
    "Tidak Ada",
    "Macan pemarah",
    "Buaya Depok",
    "Beruang sunda",
    "Tutup odol",
    "Tutup panci",
    "Kapal karam",
    "Gergaji mesin",
    "Tumis kangkung",
    "Gunting Tumpul",
    "Kasur Empuk",
    "Payung Robek",
    "Kulkas Kosong",
    "Piring Pecah",
    "Lem Super Lengket",
    "Keripik Garing",
    "Senter Mati",
    "Kue Kering",
    "Bantal Empuk",
    "Tali Jemuran",
    "Pagar besi",
    "Kunci gembok",
    "Batu Bata",
    "Remote TV",
    "Kompor Meledak",
    "Handuk Basah",
    "Kipas Rusak",
    "Jemuran Penuh",
    "Tisu Gulung",
    "Gelas Plastik",
    "Sendal Jepit",
    "Panci Gosong",
    "Guling Gembung",
    "Sarung Bantal",
    "Kaos Oblong",
    "Ember Bocor",
    "Celana Sobek",
    "Suki",
    "Sosok Karbit",
    "Windah Habatusauda",
    "AnjingKucing",
    "Lampu Hazard",
    "Mas Agus",
    "Tung Tung Sahur",
    "Azril",
    "Andriana",
    "Operator Horeg",
    "Sang Perintis",
    "Sang Pewaris",
    "Mas Gatot Guru Penjas",
    "Thomas Slebew",
    "KTP Ohim",
    "Thomas Alva Edi Sound",
    "Ilham Joseph",
    "Avatar Roblox",
    "Gelembung Sahabat",
    "Nasi Comot",
    "Mie Ayam",
    "NasGor Goreng",
    "NasPad Padang",
    "Mas Rusdi",
    "MBG",
    "Laba Laba Sunda",
    "OP Warnet",
    "Boneka Ambalabu",
    "Tuan Buas",
    "Sepatu Kuda",
    "Kucing AI",
    "Pahlwan Himmel",
    "Skibidi Toilet",
    "Vocaloid",
    "Steve Creative Mode",
    "Herobrine",
    "ChatGPT",
]  

print("=== Cek Khodam ===")

while True:
    nama = input("\nMasukkan namamu: ")

    khodam = random.choice(daftar_khodam)
    power = random.randint(1, 100)

    print(f"\nHalo {nama}!")
    print(f"Khodammu adalah: {khodam}")
    print(f"Tingkat kekuatan: {power}%")